services:
  frontend:
    build:
      context: ./DockerCourseFrontend/DockerCourseFrontend/.
    image: dometraindockercourse/frontend
    container_name: frontend
    ports:
      - 1234:80

  api:
    build:
      context: ./DockerCourseApi/.
      dockerfile: DockerCourseApi/Dockerfile
    image: dometraindockercourse/api
    container_name: api
    ports:
      - 17860:80

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Dometrain#123
    volumes: ["DockerCourseVolume:/var/opt/mssql"]

  database-seed:
    build:
      context: Database/
      dockerfile: Dockerfile
    container_name: database-seed
    depends_on: [database]

volumes:
  DockerCourseVolume:
