services:
  integration-tests:
    build:
      context: ./DockerCourseApi/.
      dockerfile: DockerCourseApi.Tests/Dockerfile
    image: dometraindockercourse/integration-tests
    container_name: integration-tests
    environment:
      - DOCKERCOURSEAPI_ConnectionString='Server=tcp:database;Initial Catalog=podcasts;Persist Security Info=False;User ID=sa;Password=Dometrain#123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;'
    depends_on:
      database-seed:
        condition: service_completed_successfully
