name: build-frontend

on:
  push:
    branches:
      - "master"
      - "ci-with-compose"
    paths:
      - "DockerCourseFrontend/**"
      - ".github/workflows/build-frontend.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./DockerCourseFrontend/DockerCourseFrontend/.
          file: ./DockerCourseFrontend/DockerCourseFrontend/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/frontend:latest
            ${{ vars.DOCKER_USERNAME }}/frontend:${{github.run_number}}
